i was trying to deploy it with vercel, but its showing errors. Double check and see if there is a problem:
Deployment Details
Build Failed
Command "npm run build" exited with 1

Created

bilaltayyab
4h ago
Status
Error
Latest
Time to Ready
30s
4h ago
Environment
Production
Domains
prehog-git-master-bilaltayyabs-projects.vercel.app
prehog-pca5a7jei-bilaltayyabs-projects.vercel.app
Source
master
7c6cfe8
Create PostHogInit.tsx

Deployment Configuration
Fluid Compute
Deployment Protection
Skew Protection
Build Logs
44s

All Logs (43)

Errors (15)

Warnings (0)
Find in logs
CtrlF
 ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/404". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout
    at o (/vercel/path0/.next/server/chunks/279.js:5:77236)
    at d (/vercel/path0/.next/server/chunks/279.js:3:32299)
    at n (/vercel/path0/.next/server/chunks/143.js:6:1187)
    at nL (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:46773)
    at nF (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:48548)
    at nF (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:64360)
    at nq (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:67434)
    at nH (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:65009)
    at nV (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:70865)
    at nz (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:69548)
Error occurred prerendering page "/_not-found". Read more: https://nextjs.org/docs/messages/prerender-error
Export encountered an error on /_not-found/page: /_not-found, exiting the build.
 ⨯ Next.js build worker exited with code: 1 and signal: null
Error: Command "npm run build" exited with 1